name             'ambari'
maintainer       'Lin He'
maintainer_email 'he9lin@gmail.com'
license          'All rights reserved'
description      'Installs/Configures Apache Ambari server and agents'
long_description 'Installs/Configures Apache Ambari server and agents'
version          '0.1.0'

depends 'yum',       '2.4.4'
depends 'hostsfile', '2.4.5'
